### ISSUE TITLE
Support for URL

### ISSUE THREAD

**Issue by nil-ableton** [AbletonAG/aqt-stylesheets#4]
URL values can be included in a CSS file as described in the W3 document: 
    http://dev.w3.org/csswg/css2/syndata.html#uri

Using such url values would help with locating resources/assets/etc..

I would expect the Style engine to resolve urls for me automatically and return an absolute URL resolved from the path containing the stylesheet itself (as described in the standard)

With a CSS file like so:
```
ComponentA {
    image: url(assets/images/hello.png)
}
```

And a qml file
```
ComponentA {
    Component.onCompleted: {
        console.log('image', StyleSet.props.url("image");
    }
}
```

Would return
```
file:///<directory containing the css>/assets/image/hello.png
```

**Comment by gck-ableton** [comment]
This is implemented with Aqt.StyleSheets 1.2.  Thus closing this request.

**Comment by nil-ableton** [comment]
:+1:
